name: Fly
author: ImMagDev\Main
api: 
- 4.0.0
version: "1.0.0"

commands:
    fly:
      description: Plugin for test
      permission: fly.use

permissions:
  fly.use:
    description: plugin for test
    default: true